export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';
export const FETCH_BOOKS = 'FETCH_BOOKS';

export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';